### ISSUE TITLE
Switch between http and https

### ISSUE THREAD

**Issue by feedm3** [ben-gibson/remote-repository-mapper#12]
It would be nice to switch between http and https.

Currently https is always used (which is correct most of the time I think) but one of my gitlab server doesn't support https so I always get an error in the browser.

Nice implementation could look like an additional checkbox in the settings with "Use https" (which is active by default).

**Comment by ben-gibson** [comment]
Seems reasonable. I will get it added in this week.

**Comment by ben-gibson** [comment]
I think it might even be nice to have this option default to http allowing the client server to decide how to handle http. GitHub, GitLab, BitBucket all redirect to https as expected.

**Comment by ben-gibson** [comment]
This is provisionally solved in #13.

**Comment by ben-gibson** [comment]
Updated should now be available.
