### ISSUE TITLE
404 when branch does not exist any more on remote

### ISSUE THREAD

**Issue by krixon** [ben-gibson/remote-repository-mapper#6]
For example:

1. Create a branch on Stash
2. Fetch the branch locally
3. Delete the branch on Stash
4. Try to view the remote file
5. 404

It would be great if this could be handled so that the plugin falls back to master when the remote branch no longer exists.

**Comment by ben-gibson** [comment]
Ah yes, I haven't accounted for this beyond checking there is a remote tracking branch locally. I will take a look once I have finished my changes in "add-support-for-more-remote-providers"

**Comment by ben-gibson** [comment]
I have added this with ls-remote [here](https://github.com/ben-gibson/remote-repository-mapper/blob/check-branch-exists-on-remote/src/uk/co/ben_gibson/repositorymapper/Repository/Repository.java#L104) #11. It does add a noticeable amount of delay but I don't think there are any better alternatives.

**Comment by ben-gibson** [comment]
Done and released in 1.3
