### ISSUE TITLE
Simple Query...

### ISSUE THREAD

**Issue by gamename** [ben-gibson/remote-repository-mapper#8]
Hi Guy,

Your plugin is very popular and looks to be well written. Its clear you put a lot of work in it, so it obviously deserves a look.

The problem is, I cannot figure out why it is useful.  :)  Could you explain when someone would want to use it?  In other words, what are the use cases? 

This is not to insult you or just be a troll.  My guess is that I'm not the only one who doesn't "get it".

Thanks for listening.

-T

**Comment by ben-gibson** [comment]
Hello,

It's a really simple plugin, and it doesn't really do much so I get why you think it's useless/shit. 

I personally found it a ball ache having to open my browser and search around my remote repository for the block of code I'm looking at in PhpStorm, finding the right branch and line number etc each time I want to discuss/share that block of code with someone. Past providing a shortcut to do this for you so you can share that link with someone or just get to it in the remote repository it doesn't do anything.

Other than that I just felt like giving Java a go and experimenting with Jetbrains plugins so in short it's a really trivial plugin.

**Comment by gamename** [comment]
Thanks for the reply.  No, I do not think its shit. :)  Now that you pointed out what it fixes for you, it makes perfect sense.  Pretty cool, actually.
